### ISSUE TITLE
JavaScript error: missing i18next.js module

### ISSUE THREAD

**Issue by garrett** [flathub/com.github.ransome1.sleek#1]
Hi! I use todo.txt already and was excited to see screenshots of sleek a few weeks ago. I was happy to see sleek appear on Flathub too (meaning I could now easily install it on Fedora Silverblue).

After installing, I tried running sleek and nothing showed up, so I ran the flatpak at the command line (`/var/lib/flatpak/exports/bin/` is in my path):

```
$ com.github.ransome1.sleek

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module './dist/cjs/i18next.js'
Require stack:
- /app/sleek/resources/app.asar/node_modules/i18next/index.js
- /app/sleek/resources/app.asar/src/configs/i18next.config.js
- /app/sleek/resources/app.asar/src/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/sleek/resources/app.asar/node_modules/i18next/index.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
```

I guess some JS libraries aren't included in the flatpak at the moment?

Anyway, it looks really cool. And thanks for the extra effort to package it as a flatpak!

**Comment by ransome1** [comment]
Hi Garret. 

Thanks for your feedback.

I am currently working on that, but I need help from the Flatpak community as I can't figure it out myself. I asked in Flatpak forums for help: https://discourse.flathub.org/t/build-successful-but-electron-app-is-missing-at-least-a-js-module/965

As soon as I got the solution I will provide a working build. For the time being you can get a working build from Snap Store or download the binaries: https://github.com/ransome1/sleek/releases/tag/v0.4.1

Best
Robin

**Comment by ransome1** [comment]
Hi @garrett . Please try a `flatpak update`. The problem should be fixed.

**Comment by garrett** [comment]
Wow, awesome! That was quick. Thank you!

Confirmed working here. 👍🏼
